✨ feat: Date Picker 컴포넌트 작성
dnd-side-project/dnd-10th-2-frontend pull request #42
Opened 2024-03-18 12:09 UTC by shubug1015

## 🛠 관련 이슈

- Resolved: #3 

## 🌱 PR 포인트

- Date Picker 컴포넌트 작성 완료했습니다.

## 📸 스크린샷 / 링크

| 클릭 | 스와이프 |
| :------: | :------: |
| <img src="https://github.com/dnd-side-project/dnd-10th-2-frontend/assets/61397627/5afca081-0374-46f8-a868-0838de2f4a62" width="330" /> | <img src="https://github.com/dnd-side-project/dnd-10th-2-frontend/assets/61397627/6c25266b-1220-46a4-9d61-bac4d572b35f" width="330" /> |

## 📎 레퍼런스

- [Swiper](https://swiperjs.com/swiper-api#events)

## ❗ 이슈사항 / 기타사항 / 에러슈팅

2024-03-18 23:06 UTC, kongnayeon requested changes
구현하기 까다로우셨을 텐데 고생 많이 하셨습니다 🥹

2024-03-18 23:06 UTC, kongnayeon commented on src/components/common/DatePicker/DatePicker.tsx
> +const DatePicker = () => {
DatePickerProps로 value, setValue 내려 줘야 훅폼으로 관리할 수 있을 것 같아요!

2024-03-19 05:29 UTC, shubug1015 commented on src/components/common/DatePicker/DatePicker.tsx
> +const DatePicker = () => {
앗 그렇네요 수정하겠습니당!

2024-03-20 12:55 UTC, kongnayeon approved these changes

2024-03-20 15:13 UTC, merged